##searxng##
version: "3.7"
services:
  redis:
    container_name: valkey_redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      #- searxng_searxng
      - ollama_default
    volumes:
      - valkey-data2:/data
      #- valkey:/usr/local/etc/valkey
      #- valkey.conf /usr/local/etc/valkey/valkey.conf
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE # Discretionary Access Control bypass file_rwx permission
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: "1"
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      #- searxng_searxng
      - ollama_default
    ports:
      - 7777:8080
    volumes:
      #- ./searxng_img:/usr/local/searxng/searx/static/themes/simple/img:rw
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: "1"

networks:
  ollama_default:
    external: true

volumes:
  valkey-data2: null
  valkey: null
